# Generated by Django 2.2.7 on 2019-11-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('description', models.TextField()),
                ('offers', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='GallaryDetails',
        ),
    ]
