# Generated by Django 2.2.7 on 2019-11-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnk', '0002_auto_20191106_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='titledetails',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
