# Generated by Django 2.2.7 on 2019-11-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnk', '0003_titledetails_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('timestamp', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=100)),
                ('lName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('dob', models.DateTimeField()),
                ('sex', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('timestamp', models.TimeField()),
                ('regTime', models.DateTimeField()),
            ],
        ),
    ]
