# Generated by Django 2.2.7 on 2019-11-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnk', '0004_destination_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='titledetails',
            name='subtitle',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
